.\" Manpage for dchat.
.\" Contact christoph.mahrl@gmail.com to correct errors or typos.

.TH man 1 "15 June 2014" "1.0" "dchat man page"
.SH NAME
dchat \- peer-to-peer chat client
.SH SYNOPSIS
dchat <INT> <LPORT> <NICK> [<DST> <RPORT>]

.SH DESCRIPTION

.SH OPTIONS

.SH SEE ALSO

.SH BUGS
No known bugs.

.SH AUTHOR
Christoph Mahrl (christoph.mahrl@gmail.com)
